[features]
seeds = false
skip-lint = false
[programs.devnet]
mint_nft = "3HuV1jdz7jqHYgVF7FvA5vG6wmcbcAXqabSatcZ5g2F6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/macmini/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
